"""Datos públicos compartidos por la interfaz y los informes."""

APP_NAME = "CPU Scheduler"
VERSION = "1.0.0"
AUTHOR = "Aníbal Pedraza Dorado"
COPYRIGHT_YEAR = "2024–2026"
REPOSITORY_URL = "https://github.com/anibalpedraza/CPU_Scheduler"
CODE_LICENSE = "MIT"
CONTENT_LICENSE = "CC BY 4.0"
CONTENT_LICENSE_URL = "https://creativecommons.org/licenses/by/4.0/"
